In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error as MAPE
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split

import os
import logging

In [16]:
# In Python, calling logging.getLogger(name) multiple times with the exact same name will neither overwrite the logger nor create multiple copies
# ; instead, it will always return a reference to the exact same singleton object. 

# However, how you configure that logger can cause an unexpected side effect: it will create multiple copies of your log outputs (duplicated logs)
# if you keep adding handlers to it

logger_name = '1_Data_Ingestion'

def create_logger_handler(log_folder, logger_name):
    # Ensure log directory exists
    log_dir = log_folder
    os.makedirs(log_dir, exist_ok=True)

    # logging configuration
    logger = logging.getLogger(logger_name)
    logger.setLevel('DEBUG')


    # This is to print at console level
    console_handler = logging.StreamHandler()
    console_handler.setLevel('DEBUG')

  # This is to print in log file
    file_path = os.path.join(log_dir, logger_name+'.log')
    file_handler = logging.FileHandler(file_path)
    file_handler.setLevel('DEBUG')

    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    file_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    logger.addHandler(file_handler)

    return logger

logger = create_logger_handler('../logs', logger_name)

# If we want to diable the logger
# logging.getLogger("Data_Ingestion").disabled = True

# If we disable logger then we can again enable it by just triggering above cell again. Logger will automatically enable it.

In [15]:
# If we have run above code multiple times then we will have multiple handlers which results in printing same output twice/thrice
# We can remove active handlers but we can't remove logger

def close_remove_active_handler(logger_name):

    # active log handlers
    logger = logging.getLogger(logger_name)
    print(f'Active handlers for logger- {logger_name} is -', len(logger.handlers))

    for handler in logger.handlers[:]:
        handler.close()
        logger.removeHandler(handler)

    print(f'Active handlers for logger- {logger_name} is -', len(logger.handlers))

close_remove_active_handler(logger_name)

Active handlers for logger- 1_Data_Ingestion is - 2
Active handlers for logger- 1_Data_Ingestion is - 0

In [17]:
def load_data(path):
    """ Loading data """
    
    try:
        logger.debug('Data load has started')
        df = pd.read_csv(path)
        logger.debug('Data loaded successfully from : %s', path)
        return df
    except Exception as e:
        logger.error('Unexpected error occurred while loading the data: %s', e)
        raise

In [33]:
def save_data(df, raw_path, train_path, test_path):
    """ Saving Data """

    try:
        logger.debug('Saving raw data has started')

        df.to_csv(raw_path, index=None)

        logger.debug('Raw Data saved successfully')


        logger.debug('Saving train_test data has started')

        train_data, test_data = train_test_split(df, test_size=0.2, random_state=123, shuffle=True)
        train_data.reset_index(drop=True, inplace=True)
        test_data.reset_index(drop=True, inplace=True)

        train_data.to_csv(train_path, index=None)
        test_data.to_csv(test_path, index=None)

        logger.debug('Train_Test Data saved successfully')



    except Exception as e:
        logger.error('There was some error while saving data - ', e)
        raise

In [34]:
reading_path = 'https://github.com/ashish-sangwan18/Datasets/raw/refs/heads/main/wagedata.csv'
df = load_data(reading_path)


raw_path = '../data/raw/' + 'Raw_Data.csv'
train_path = '../data/Train_Test/' + 'Train_Data.csv'
test_path = '../data/Train_Test/' + 'Test_Data.csv'

save_data(df, raw_path, train_path, test_path)

2026-06-08 08:10:42,800 - 1_Data_Ingestion - DEBUG - Data load has started

2026-06-08 08:10:46,338 - 1_Data_Ingestion - DEBUG - Data loaded successfully from : https://github.com/ashish-sangwan18/Datasets/raw/refs/heads/main/wagedata.csv
2026-06-08 08:10:46,343 - 1_Data_Ingestion - DEBUG - Saving raw data has started
2026-06-08 08:10:46,431 - 1_Data_Ingestion - DEBUG - Raw Data saved successfully
2026-06-08 08:10:46,440 - 1_Data_Ingestion - DEBUG - Saving train_test data has started
2026-06-08 08:10:46,569 - 1_Data_Ingestion - DEBUG - Train_Test Data saved successfully

In [23]:
df.head()

   Wage  Education  Experience  Age
0  5100          8          21   35
1  4950          9          42   57
2  6670         12           1   19
3  4000         12           4   22
4  7500         12          17   35

In [24]:
x = df.iloc[:,1:]
y = df.iloc[:,0:1] #Target - Wage

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123, shuffle=True)

# Dropping index
x_train.reset_index(drop=True, inplace=True)
x_test.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(427, 3) (427, 1) (107, 3) (107, 1)

In [26]:
train_data, test_data = train_test_split(df, test_size=0.2, random_state=123, shuffle=True)

In [27]:
train_data.shape

(427, 4)

In [25]:
x_train.head()

   Education  Experience  Age
0         14          15   35
1         12           9   27
2         16           8   30
3         11           3   20
4         12           9   27